name: JavaGoat-WhatsApp-Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # Yeh har 5 ghante mein bot ko automatic restart karega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install Dependencies
      run: npm install

    - name: Start AI Bot
      run: npm start
